"""add plano-aluno

Revision ID: 8183f163ea0f
Revises: efc042e6c657
Create Date: 2025-11-29 00:37:54.134859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8183f163ea0f'
down_revision: Union[str, None] = 'efc042e6c657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=20), nullable=False),
    sa.Column('frequencia', sa.Integer(), nullable=False),
    sa.Column('valor_mensal', sa.Float(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('politica_cancelamento', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planos_id'), 'planos', ['id'], unique=False)
    op.create_foreign_key(None, 'alunos', 'planos', ['plano_id'], ['id'])
    op.drop_column('alunos', 'planos_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alunos', sa.Column('planos_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'alunos', type_='foreignkey')
    op.drop_index(op.f('ix_planos_id'), table_name='planos')
    op.drop_table('planos')
    # ### end Alembic commands ###
